services:
  pg14-export:
    image: postgres:14
    container_name: pg14-export
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - database_pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  database_pgdata:
    external: true

