services:
  postgres:
    image: postgres:16
    container_name: project-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - backend_network
    command: >
      postgres -c max_connections=100
               -c shared_buffers=1536MB
               -c effective_cache_size=3GB
               -c work_mem=16MB
               -c maintenance_work_mem=256MB
               -c wal_buffers=16MB
               -c min_wal_size=1GB
               -c max_wal_size=4GB
               -c checkpoint_completion_target=0.9
               -c max_parallel_workers=2
               -c max_worker_processes=2
               -c max_parallel_workers_per_gather=1
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2500M
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: project-redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ../infrastructure/cache/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - backend_network
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 512M
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: project-nginx
    restart: always
    volumes:
      - ../infrastructure/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ../infrastructure/static:/app/infrastructure/static:ro
    ports:
      - "80:80"
    networks:
      - backend_network
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 256M

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: project-app
    depends_on:
      - postgres
      - redis
    expose:
      - "8000"
    networks:
      - backend_network
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      - REDIS_URL=${REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
      - SALT=${SALT}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 2048M
    restart: unless-stopped

networks:
  backend_network:
    driver: bridge

volumes:
  pgdata:
    external: true
  redis_data:
    external: true
