services:
  postgres:
    image: postgres:16
    container_name: test-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data/pgdata
    networks:
      - test_network
    command: >
      postgres -c max_connections=50
               -c shared_buffers=768MB
               -c effective_cache_size=1500MB
               -c work_mem=8MB
               -c maintenance_work_mem=128MB
               -c wal_buffers=8MB
               -c min_wal_size=512MB
               -c max_wal_size=2GB
               -c checkpoint_completion_target=0.9
               -c max_parallel_workers=2
               -c max_worker_processes=2
               -c max_parallel_workers_per_gather=1
               -c listen_addresses='*'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 1536M
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: test-redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ../infrastructure/cache/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - test_network
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 256M
    restart: unless-stopped

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: test-app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ..:/app
    expose:
      - "8000"
    ports:
      - "8000:8000"
    networks:
      - test_network
    environment:
      DATABASE_URL: postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      SALT: ${SALT}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: "0.9"
          memory: 1280M
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: test-nginx
    restart: always
    volumes:
      - ../infrastructure/nginx/nginx.test.conf:/etc/nginx/conf.d/default.conf:ro
      - ../infrastructure/static:/app/infrastructure/static:ro
    ports:
      - "80:80"
    networks:
      - test_network
    depends_on:
      - app
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 128M

networks:
  test_network:
    driver: bridge

volumes:
  pgdata_test:
    external: true
    name: standart_s_pgdata_test

  redis_data:
    external: true
    name: redis_data
